version: '3'

services:
  slackmirror:
    image: omercnet/slackmoderator
    build: .
    environment:
      LOG_LEVEL: INFO 
      PORT: 3000
      SLACK_SIGNING_SECRET: 
      SLACK_BOT_TOKEN: 
      SLACK_ADMIN_TOKEN: 
      MODERATE_CONTENT_KEY: 
      REDIS_URL: redis://redis
    ports:
      - 127.0.0.1:3000:3000
  redis:
    image: redis:7-alpine
    volumes:
      - .redis:/data
    ports:
      - 127.0.0.1:6378:6379
